= Introduction

The Privacy Sandbox initiative was launched by Google in 2019 to reduce cross-site and cross-app tracking. As part of this project, Google proposed several alternative mechanisms to restrict the use of third-party cookies, fingerprinting techniques, and other identifiers while still supporting key use cases such as advertising, bot and spam protection, conversion measurement, etc.

Over the past few years, Google has implemented, shipped, and deprecated some of these new APIs and technologies directly into their products (Chrome, Android, etc.). Google often did so without reaching consensus with other web browsers (e.g., Brave, Mozilla, Safari, etc.) on standardization and on these new proposals' privacy claims. This raised several concerns about the potential of these mechanisms put forward by Google to fundamentally disrupt the advertising, mobile, and web ecosystems. As a result, we believe that it is important to transcend the debate around the somewhat controversial nature of Google’s project to ask the following questions: _how can we contribute as a research community to the discussions about the Privacy Sandbox (and similar proposals put forward by others) and have real impact to protect the privacy of billions of users?_ Indeed, it appears paramount for researchers to understand the consequences that these new technologies (and future ones) will have on real users if and when deployed.

In the following report, we outline our call for privacy, security, usability, and utility evaluations of these APIs. Concretely, our efforts materialized through the creation and operation of #link("https://privacysandstorm.github.io")[*Privacy Sandstorm*]\; a research portal presenting a roadmap to these rapidly evolving changes, systematically gathering and publishing resources (overview, analyses, artifacts, etc.) about such proposals, and giving broader visibility to the research findings in that space. The Privacy Sandstorm website was launched during our HotPETS 2024 talk #cite(<beuginNeedResearchSandstormPrivacySandbox2024>) with the goal to spark and coordinate a conversation among attendees on the steps that we should take, as a research community, to better understand these changes and play a part in them.

As we systematically list and provide visibility to all research findings in that space, we find that we offer a broader perspective on the findings related to the Privacy Sandbox than what Google lets show through their official channels. We expect our resources to not only be useful to the academic and industry communities, but also to encourage people to contribute to them (open to suggestions, either by message or directly through opening a pull request on the repository) and join our endeavor (see invite link to communication workspace on website).


